name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Sync Files
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -o BatchMode=yes" \
            --exclude='.git' \
            --exclude='node_modules' \
            ./ numa-desarrollo@34.71.107.222:/home/numa-desarrollo/numa-reporteador-backend

      - name: Update Service
        run: |
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes numa-desarrollo@34.71.107.222 \
            "cd /home/numa-desarrollo/numa-reporteador-backend && \
            chmod +x update-service.sh && \
            ./update-service.sh backend"